# Generated by Django 2.1.3 on 2018-11-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_auto_20181112_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
